apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: issuebell
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/back1ash/IssueBell.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: issuebell
  ignoreDifferences:
  - group: cert-manager.io
    kind: ClusterIssuer
    jsonPointers:
    - /status
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    jsonPointers:
    - /status
  syncPolicy:
    automated:
      prune: true       # delete resources removed from git
      selfHeal: true    # revert manual changes in cluster
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
