apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: issuebell-com-tls
  namespace: gateway
spec:
  secretName: issuebell-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - issuebell.com
