apiVersion: v1
kind: ConfigMap
metadata:
  name: issuebell-config
  namespace: issuebell
data:
  DISCORD_REDIRECT_URI: "https://issuebell.com/auth/callback"
  GITHUB_REDIRECT_URI: "https://issuebell.com/auth/github/callback"
  POLL_INTERVAL: "180"
  ADMIN_DISCORD_ID: "270510544241295360"
