apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: issuebell-to-gateway
  namespace: gateway
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: issuebell
  to:
  - group: gateway.networking.k8s.io
    kind: Gateway
