apiVersion: v1
kind: Secret
metadata:
  name: issuebell-secret
  namespace: issuebell
type: Opaque
stringData:
  SECRET_KEY: ""
  DISCORD_BOT_TOKEN: ""
  DISCORD_CLIENT_ID: ""
  DISCORD_CLIENT_SECRET: ""
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
  GITHUB_WEBHOOK_SECRET: ""
