apiVersion: v1
kind: Service
metadata:
  name: issuebell
  namespace: issuebell
spec:
  selector:
    app: issuebell
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
